<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nur Aqilah Salma Abiyyah">
<meta name="dcterms.date" content="2024-01-21">

<title>Pengaruh Impor Beras Asal Thailand Terhadap Ketahanan Pangan Indonesia Periode 2010-2019</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Impor Beras Asal Thailand Terhadap Ketahanan Pangan Indonesia Periode 2010-2019</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nur Aqilah Salma Abiyyah </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 21, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Selama dekade 2010-2019, impor beras dari Thailand telah menjadi faktor yang signifikan dalam memengaruhi ketahanan pangan Indonesia. Indonesia sebagai negara dengan populasi yang besar dan pertumbuhan ekonomi yang pesat menghadapi tantangan untuk memenuhi kebutuhan pangan domestik. Thailand sebagai salah satu produsen dan eksportir beras terbesar di dunia, menjadi pemasok utama bagi Indonesia.</p>
<p>Ketergantungan Indonesia pada impor beras dari Thailand sebagai solusi untuk mengatasi defisit produksi domestik. Meskipun impor dapat memberikan akses terhadap pasokan beras yang mencukupi, kebijakan ini juga meningkatkan risiko terhadap fluktuasi harga dan volatilitas pasar internasional. Selain itu, impor beras juga dapat mempengaruhi mata rantai pasok pangan nasional, menggerus keberlanjutan pertanian lokal dan kemandirian pangan. Oleh karena itu, penting untuk mengkaji pengaruh impor beras asal Thailand terhadap ketahanan pangan Indonesia selama periode tersebut.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini akan fokus pada pengaruh impor beras asal Thailand terhadap ketahanan pangan Indonesia selama periode 2010-2019. Ruang lingkup penelitian mencakup pengaruh impor beras terhadap keseimbangan antara ketersediaan beras, jumlah penduduk, dan tingkat konsumsi dalam upaya mencapai ketahanan pangan di Indonesia.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>Berdasarkan uraian latar belakang diatas maka yang menjadi masalah pokok pada penelitian ini adalah:</p>
<ol type="1">
<li><p>Bagaimana hubungan antara variabel X, variabel Y, dan konsumsi beras dalam periode 2010-2019?</p></li>
<li><p>Bagaimana pengaruh impor beras terhadap keseimbangan antara ketersediaan beras, jumlah penduduk, dan tingkat konsumsi dalam upaya mencapai ketahanan pangan di Indonesia?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan dari penelitian ini adalah untuk menganalisis pengaruh impor beras asal Thailand terhadap ketahanan pangan Indonesia selama periode 2010-2019. Penelitian ini bertujuan untuk memahami hubungan antara variabel impor beras (X), jumlah penduduk (Y), dan konsumsi beras, dengan fokus pada pengaruhnya terhadap ketersediaan pangan domestik. Selain itu, penelitian ini bertujuan untuk mengevaluasi efektivitas kebijakan impor beras yang diterapkan oleh pemerintah Indonesia serta menjelajahi faktor demografis yang mungkin mempengaruhi dinamika ketahanan pangan. Hasil penelitian diharapkan dapat memberikan wawasan bagi pengambil kebijakan dalam meningkatkan ketahanan pangan Indonesia.</p>
<p>Adapun manfaat dari penelitian ini antara lain:</p>
<ol type="1">
<li>Manfaat Teoritis</li>
</ol>
<p>Manfaat teoritis dari penelitian ini mencakup pemahaman mendalam tentang keterkaitan antara impor beras dari Thailand dan ketahanan pangan Indonesia, membantu pembuat kebijakan, praktisi, dan peneliti untuk mengembangkan strategi yang lebih baik dalam mengelola ketahanan pangan nasional.</p>
<ol start="2" type="1">
<li>Manfaat Praktis</li>
</ol>
<ol type="A">
<li>Bagi Penulis</li>
</ol>
<p>Hasil penelitian ini memberikan manfaat praktis bagi penulis dengan meningkatkan keahlian analisis data menggunakan RStudio dan memperdalam pemahaman tentang impor beras asal Thailand dan ketahanan pangan di Indonesia. Penulis dapat mengaplikasikan keterampilan ini dalam penelitian selanjutanya.</p>
<ol start="2" type="A">
<li>Bagi Instansi</li>
</ol>
<p>Hasil Penelitian ini memberikan manfaat praktis bagi instansi terkait, seperti Kementerian Perdagangan atau Lembaga Statistik. Temuan ini dapat menjadi dasar untuk untuk meningkatkan ketahanan pangan Indonesia di tengah dinamika impor beras dari Thailand.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan sebagai penunjang regresi multivariat dalam penelitian ini antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li>Ketahanan Pangan</li>
</ol>
<p>Ketahanan Pangan mencerminkan kemampuan suatu entitas, baik itu negara, wilayah, atau individu, untuk menjamin ketersediaan pangan yang cukup, aman, bergizi, dan terjangkau bagi seluruh populasi sepanjang waktu. Aspek pertama dalam konsep ini adalah ketersediaan pangan, yang berkaitan erat dengan produktivitas sektor pertanian dan kemampuan memenuhi kebutuhan pangan melalui sumber daya alam. Selanjutnya, akses pangan menjadi aspek penting, melibatkan kemampuan individu atau kelompok untuk mendapatkan pangan secara fisik, ekonomis, dan sosial, termasuk distribusi dan stabilitas harga. Aspek lainnya adalah pemanfaatan pangan, yang menitikberatkan pada nutrisi dan kesehatan masyarakat. Ketahanan pangan juga mencakup stabilitas sistem pangan, di mana keberlanjutan dan kestabilan sistem tetap terjaga dalam menghadapi guncangan eksternal seperti perubahan iklim, bencana alam, atau krisis ekonomi. Kesadaran dan keterlibatan masyarakat menjadi dimensi penting, di mana pemahaman akan pentingnya pola makan sehat, pertanian berkelanjutan, dan kebijakan pangan yang baik dapat memperkuat ketahanan pangan secara menyeluruh. Ketahanan pangan yang baik memiliki dampak positif langsung terhadap kesejahteraan sosial, ekonomi, dan politik, menciptakan landasan yang kuat untuk stabilitas dan keberlanjutan pemenuhan kebutuhan pangan.</p>
<ol start="2" type="1">
<li>Impor</li>
</ol>
<p>Impor adalah kegiatan membeli barang atau jasa dari negara lain untuk digunakan di dalam negeri. Praktik impor merangkum sejumlah proses, termasuk pembelian, pengangkutan, dan pembayaran barang atau jasa dari pemasok asing. Negara-negara melakukan impor untuk mendapatkan barang atau jasa yang tidak dapat diproduksi atau tidak tersedia secara efisien di dalam negeri, atau untuk memenuhi permintaan yang melebihi kapasitas produksi domestik. Dalam era globalisasi, impor telah menjadi bagian integral dari perekonomian modern. Proses impor melibatkan negosiasi kontrak antara importir dan eksportir, termasuk penetapan harga, persyaratan kualitas, dan metode pembayaran. Setelah itu, barang atau jasa diangkut melalui jalur perdagangan internasional, seperti pelabuhan atau bandara, dan dikenakan bea cukai serta pajak impor.</p>
<p>Sitasinya, impor memainkan peran penting dalam memperluas akses pasar, meningkatkan keragaman produk, dan memfasilitasi pertukaran internasional. Namun, impor juga dapat menciptakan tantangan, seperti defisit perdagangan, ketergantungan eksternal, dan fluktuasi nilai tukar. Oleh karena itu, manajemen impor yang efektif dan kebijakan perdagangan yang bijaksana menjadi krusial untuk menjaga keseimbangan ekonomi suatu negara, mengoptimalkan keuntungan, dan menjaga ketahanan perekonomian nasional.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>Impor (Y)</th>
<th>Jumlah Penduduk (X)</th>
<th>KONSUMSI BERAS (S)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2010</td>
<td>209.127,8</td>
<td>241.8</td>
<td>33189891</td>
</tr>
<tr class="even">
<td>2011</td>
<td>938.695,7</td>
<td>245.1</td>
<td>33673006</td>
</tr>
<tr class="odd">
<td>2012</td>
<td>315.352,7</td>
<td>248.5</td>
<td>34150917</td>
</tr>
<tr class="even">
<td>2013</td>
<td>94.633,9</td>
<td>251.8</td>
<td>34623039</td>
</tr>
<tr class="odd">
<td>2014</td>
<td>366.203,5</td>
<td>255.1</td>
<td>31268435</td>
</tr>
<tr class="even">
<td>2015</td>
<td>126.745,7</td>
<td>258.4</td>
<td>33144541</td>
</tr>
<tr class="odd">
<td>2016</td>
<td>557.890,0</td>
<td>261.6</td>
<td>33470000</td>
</tr>
<tr class="even">
<td>2017</td>
<td>108.944,8</td>
<td>264.6</td>
<td>29130000</td>
</tr>
<tr class="odd">
<td>2018</td>
<td>795.600,1</td>
<td>265</td>
<td>26300000</td>
</tr>
<tr class="even">
<td>2019</td>
<td>53.278,0</td>
<td>267</td>
<td>31310000</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data sekunder dengan bentuk data time series 2010-2019, data yang dipakai ialah data yang telah diolah dengan sumber Badan Pusat Statistik.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'BERAS.xlsx'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x<span class="sc">+</span>s, <span class="at">data=</span>dat)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>x,dat<span class="sc">$</span>m,<span class="at">xlab=</span><span class="st">"Impor"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>) <span class="co">#membuat garis horizontal di y=0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Teknik analisis yang digunakan dalam penelitian ini adalah teknik kuantitatif deskriptif. Metode yang dipilih adalah regresi multivariat dengan tujuan untuk mencari hubungan antara Impor Beras (Y) dengan Jumlah penduduk (X) dan Jumlah Konsumsi Beras (S). Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
Y=\beta_0 +\beta_1 X+\beta_2 S+\mu
\]</span></p>
<p>Di mana X adalah Impor Beras Thailand, S adalah Jumlah penduduk Indonesia, dan Y adalah Konsumsi Beras.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std.Error</th>
<th>t-value</th>
<th>Pr(&gt;</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intecerpt</td>
<td>3.265e+07</td>
<td>1.338e+06</td>
<td>24.399</td>
<td>8.5e-09</td>
</tr>
<tr class="even">
<td>X</td>
<td>-1.762e+00</td>
<td>2.892e+00</td>
<td>-0.609</td>
<td>0.559</td>
</tr>
<tr class="odd">
<td>R&nbsp;squared</td>
<td>0.04437</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Adjusted&nbsp;R-Squared</td>
<td>-0.07508</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>F-Statistic</td>
<td>0.3715</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Analisis regresi linear menunjukkan hasil yang signifikan terkait pengaruh variabel impor beras (X) terhadap jumlah penduduk dan konsumsi beras. Dalam tabel estimasi regresi, terdapat dua baris yang mencakup intersep dan koefisien variabel X. Untuk nilai intersep (intercept), diperoleh perkiraan sebesar 3.265e+07, dengan kesalahan standar sebesar 1.338e+06. Meskipun nilai t-value sekitar 24.399, indikasi tidak signifikan secara statistik terhadap model ini didukung oleh nilai p-value yang tinggi, yaitu 8.5e-09. Ini menandakan bahwa variabel intersep memberikan kontribusi signifikan terhadap prediksi impor beras. Kemudian, pada variabel Y (impor), koefisien regresi diperkirakan sebesar -1.762e+00, dengan kesalahan standar 2.892e+00. Nilai t-value sekitar -0.609, dan p-value sebesar 0.559. Angka-angka ini mengindikasikan bahwa variabel impor memiliki pengaruh yang signifikan terhadap model regresi. Koefisien positif menunjukkan bahwa peningkatan jumlah penduduk dan konsumsi beras berkontribusi pada peningkatan impor beras.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"BERAS.xlsx"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  TAHUN     x        s       y
  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1  2010  242. 33189891 209128.
2  2011  245. 33673006 938696.
3  2012  248. 34150917 315353.
4  2013  252. 34623039  94634.
5  2014  255. 31268435 366204.
6  2015  258. 33144541 126746.</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"BERAS.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(x<span class="sc">+</span>s<span class="sc">~</span>y, <span class="at">data=</span>dat)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = x + s ~ y, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-4952394 -1123133   808657  1988784  2672774 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.265e+07  1.338e+06  24.399  8.5e-09 ***
y           -1.762e+00  2.892e+00  -0.609    0.559    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2698000 on 8 degrees of freedom
Multiple R-squared:  0.04437,   Adjusted R-squared:  -0.07508 
F-statistic: 0.3715 on 1 and 8 DF,  p-value: 0.5591</code></pre>
</div>
</div>
<p>Analisis regresi linear sederhana dilakukan untuk memahami hubungan antara variabel Impor Beras (Y) dengan variabel Jumlah penduduk (X) dan Jumlah Konsumsi Beras (S). Hasil regresi menunjukkan bahwa intercept (nilai saat Y=0) adalah 3.265e+07, yang mewakili perkiraan Jumlah penduduk dan Jumlah Konsumsi Beras ketika Impor Beras (Y) sama dengan nol. Koefisien untuk variabel Impor Beras (Y) adalah -1.762e+00, menunjukkan perubahan yang diharapkan dalam Jumlah penduduk dan Jumlah Konsumsi Beras untuk setiap unit perubahan dalam Impor Beras. Namun, koefisien ini tidak signifikan (p-value: 0.559), menunjukkan bahwa variabel Impor Beras mungkin tidak memberikan kontribusi signifikan terhadap variabilitas dalam Jumlah penduduk dan Jumlah Konsumsi Beras. Selain itu, nilai R-squared yang rendah (0.04437) dan p-value F-statistic yang tinggi (0.5591) menunjukkan bahwa model secara keseluruhan tidak signifikan.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<ol type="1">
<li><p>Analisis regresi pada rentang waktu 2010-2019 menunjukkan bahwa tidak terdapat korelasi yang signifikan secara statistik antara impor beras ((X)) dan konsumsi beras ((Y)). Koefisien (X) tidak memiliki nilai yang signifikan (p-value = 0.559), menunjukkan bahwa dampak impor beras tidak konsisten terhadap tingkat konsumsi beras.</p></li>
<li><p>Pengaruh impor beras terhadap keseimbangan antara ketersediaan beras, jumlah penduduk, dan tingkat konsumsi tidak menunjukkan signifikansi statistik. Walaupun model regresi memberikan gambaran, koefisien (X) tidak memberikan pengaruh yang konsisten pada konsumsi beras. Oleh karena itu, dalam upaya mencapai ketahanan pangan di Indonesia, perlu dilakukan analisis mendalam terhadap kebijakan impor beras. Aspek-aspek seperti kebijakan pertanian, produksi beras lokal, dan faktor sosial-ekonomi masyarakat perlu menjadi fokus untuk merancang strategi yang lebih efektif dalam menghadapi tantangan ketahanan pangan. Pengkajian lebih lanjut terhadap faktor-faktor ini diharapkan dapat memberikan pemahaman yang komprehensif dan relevan terkait dinamika ketersediaan dan konsumsi beras di Indonesia.</p></li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Azzahra, D. M., Amir, A., &amp; Hodijah, S. (2021). Faktor-faktor yang mempengaruhi impor beras di Indonesia Tahun 2001-2019. E-Journal Perdagangan Industri Dan Moneter, 9(3), 181-192.</p>
<p>Hasanah, L. A. (2022). Analisis Faktor-Faktor Pengaruh Terjadinya Impor Beras di Indonesia Setelah Swasembada Pangan. GROWTH Jurnal Ilmiah Ekonomi Pembangunan, 1(2), 57-72.</p>
<p>Paipan, S., &amp; Abrar, M. (2020). Determinan ketergantungan impor beras di Indonesia [determinants of rice import dependency in Indonesia]. Jurnal Ekonomi &amp; Kebijakan Publik, 11(1), 53-64.</p>
<p>Prinadi, R., Yulianto, E., &amp; Mawardi, M. K. (2016). Pengaruh Nilai Tukar Rupiah, Harga Beras Internasional dan Produksi Beras Dalam Negeri Terhadap Volume Impor Beras Indonesia (Studi Impor Beras Indonesia Tahun 2002-2013) (Doctoral dissertation, Brawijaya University).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>